version: '3.2'

services:
  filebeat:
    build: .
    user: root
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /var/lib/docker/containers/
        target: /var/lib/docker/containers/
        read_only: true
    command: " ./filebeat -c filebeat.yml -e"
